sudo: required
dist: trusty
addons:
  firefox: latest
apt:
  sources:
    — google-chrome
  packages:
    — google-chrome-stable
    — google-chrome-beta
language: node_js
node_js:
  - "7"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "7"
before_install:
  - npm i npm@^5 -g
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  #- npm run ci:travis
   - npm run travis-test
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  repo: simon-an/frontend-demo
  on:
    branch: master